### ISSUE TITLE
Error building on linux

### ISSUE THREAD

**Issue by leokaplan** [grafana/simple-react-panel#14]
Just downloaded yarn and cloned this repository in a fresh ubuntu machine:

`yarn build`
```
yarn run v1.21.1
$ grafana-toolkit plugin:build
TypeError: Cannot read property 'access' of undefined
    at Object.<anonymous> (/var/lib/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:16:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/lib/grafana/plugins/simple-react-panel/node_modules/@grafana/toolkit/src/cli/index.js:13:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leokaplan** [comment]
I ran `yarn install` before

**Comment by briangann** [comment]
which version of node are you using?

we're building with v12

**Comment by leokaplan** [comment]
I was using version 8. 
Updated via nvm to version 13, worked like a charm.
Thank you!
